# -*- coding: utf-8 -*-
"""AnaliseSuicidio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F6RdJ8J3sdVAgpEEBRG3OktyRWgPnMhP
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import numpy as np
import seaborn as sns
from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("drive/My Drive/projeto2/who_suicide_statistics.csv")
df.describe()

"""<h1> Análise no mundo"""

sex = pd.DataFrame(sex, index=[""])
sex.plot.barh(title="Número de suicidos no mundo por sexo")
plt.legend(["Feminino", "Masculino"],title = "Sexo")
plt.show()

ys = df.groupby('year')['suicides_no'].sum()
ys = ys.reset_index()
ys.plot(x = 'year', y = 'suicides_no')
#numero de suicidios por ano
#percebemos uma drástica queda a partir de meados de 2014
#algumas sugestões para tal seria a visibilidade que o tema vem tomando nos ultimos anos, por meio de campanhas, midias
#maior procura a profissionais adequados, setembro amarelo, entre outros.

n_ap = df[df.suicides_no.isnull()]
x =  n_ap.groupby('year')['population'].count().index
sns.distplot(x)
#dados que nao aparecem ao longo dos anos
#vemos uma quantidade significativa que prejudica a conclusão a partir dos dados

"""<h1> Países que possuem maior frenquência no ranking de suicidios masculinos e femininos"""

a = df[df.sex=='male']
v1 = a.sort_values(by='suicides_no',ascending=False)
v1 = v1[0:500].drop('age',axis=1).drop('year',axis=1).drop('population',axis=1).drop('sex',axis=1)
q2 = v1.groupby('country').count()
q2.plot.barh(color='r')

q2.plot.hist(bins=10)

b = df[df.sex=='female']
v2 = b.sort_values(by='suicides_no',ascending=False)
v2 = v2[0:500].drop('age',axis=1).drop('year',axis=1).drop('population',axis=1).drop('sex',axis=1)
q3 = v2.groupby('country').count()
q3.plot.barh(color='b')

q3.plot.hist(bins=6)

"""<h1> Análise do suicidio no Brasil """

c = df[df.country == 'Brazil']
v3 = c.drop('country',axis=1).drop('population',axis=1).drop('sex',axis=1).drop('age',axis=1).drop('year',axis=1)
d = v3[264:]
d.sum()
# No sec XXI 137626 pessoas se suicidaram
c.describe()

v3 = c.sort_values(by='suicides_no',ascending=False)
v3 = v3[:10]
v3
#Os 10 maiores numeros de suicidio no Brasil
#Observamos a recorrência do sexo masculino e da faixa etaria entre 35-54

v4 = v3['suicides_no']
v4.plot.hist(bins=4)
#frequencia de suicidios

v4.plot.kde()

brasil = pd.read_csv("drive/My Drive/suicidiobrasil.csv")
brasil.set_index('Faixa Etária')
brasil.plot()
#as taxas de suicidio em todas as faixas não variaram tanto entre 2010-2015 mas ainda sim, 2015 apresenta os valores mais expressivos.

brasil.plot.bar(stacked=True)

x =  brasil.sort_values(by = '2010',ascending=False)
x[:1]
y =  brasil.sort_values(by = '2011',ascending=False)
y[:1]
z =  brasil.sort_values(by = '2012',ascending=False)
z[:1]
w =  brasil.sort_values(by = '2013',ascending=False)
w[:1]
t =  brasil.sort_values(by = '2014',ascending=False)
t[:1]
r =  brasil.sort_values(by = '2015',ascending=False)
r[:1]
#De 2010 - 2015 os maiores números de suicidio estão concentrados na faixa etária entre 35-54 anos